name: covid19_analysis
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - scipy
  - pandas
  - requests
  - matplotlib
  - plotly
  - statsmodels
  - jupyter
  - streamlit
  - geopandas
  - pip
  - pip:
    - uk-covid19 # the PHE library for pulling from the PHE/NHSE covid-19 api API